baseURL = 'http://sai-harsha.netlify.app/'
languageCode = 'en-us'
title = 'I Dont Know'
theme = 'ewbh'

[params]
  description = "lorem ipsum"
  placeholder="https://placehold.co/1280x720"
  alt="Image"
  author="Sai Harsha"
  links=['Posts']

[markup]
  [markup.highlight]
    linenos = true
    noClasses = true
    style = 'github-dark'
    lineNumbersInTable = false
